import cron from 'node-cron';
import { logger } from '../utils/logger.js';
import { generateResponse } from './aiService.js';
import { EmbedBuilder } from 'discord.js';

export const startCronJobs = (client) => {
    logger.info("[CRON] Starting background scheduling services...");

    // Daily AI Briefings at 8:00 AM everyday
    cron.schedule('0 8 * * *', async () => {
        logger.info("[CRON] Executing Daily AI Briefings...");

        try {
            // Note: In a real environment, you'd fetch subscribed users from Postgres.
            // For this portfolio build, we simulate sending it to a specific announcements channel.
            const prompt = `Generate a personalized morning briefing. Include a fake weather report for 'Cyber City', 3 completely fake but highly realistic tech news headlines, and a hyper-aggressive motivational quote to wake up developers.`;
            
            const briefingText = await generateResponse(prompt);

            const embed = new EmbedBuilder()
                .setTitle("🌅 Your Daily Neural Briefing")
                .setDescription(briefingText)
                .setColor('#9B59B6')
                .setFooter({ text: "Generated by Prometheus AI", iconURL: "https://cdn-icons-png.flaticon.com/512/2083/2083213.png" });

            // Send to a default channel or loop through users here.
            client.guilds.cache.forEach(guild => {
                const channel = guild.channels.cache.find(c => c.name === 'announcements' || c.name === 'general');
                if (channel) {
                    channel.send({ embeds: [embed] }).catch(() => {});
                }
            });

        } catch (error) {
            logger.error("[CRON] Failed to run daily briefing:", error);
        }
    });
};
